
package ventanas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Vehiculo;

/**
 *
 * @author Jorge Fuentes
 * @author Fernanda Jara
 * @author Javier Torres
 * @author Miriam Zambrano
 */
public class InicioListado extends javax.swing.JPanel {
    
    private DefaultTableModel dfTable;
    private Object[] obj = new Object[7];
    private MenuPrincipal mp;
    
    /**
     * Creates new form InicioListado
     */
    public InicioListado(MenuPrincipal ventana) {
        initComponents();
        setSize(740,570);
        setLocation(0,0);
        this.mp = ventana;
        dfTable = new DefaultTableModel();
        dfTable.addColumn("Marca");
        dfTable.addColumn("Modelo");
        dfTable.addColumn("Patente");
        dfTable.addColumn("Color");
        dfTable.addColumn("Año");
        dfTable.addColumn("Kilometraje");
        dfTable.addColumn("Precio");
        this.tablaVehiculos.setModel(dfTable);
        cargarListadoEnTabla(mp.getArrayList());
    }
    //Recorre el arrayList de vehiculos y los muestra en la tabla
    public void cargarListadoEnTabla(ArrayList<Vehiculo> lista){
        for(int i=0; i<lista.size(); i++){
            obj[0] = lista.get(i).getMarca();
            obj[1] = lista.get(i).getModelo();
            obj[2] = lista.get(i).getPatente();
            obj[3] = lista.get(i).getColor();
            obj[4] = lista.get(i).getAnio();
            obj[5] = lista.get(i).getKilometraje();
            obj[6] = lista.get(i).getPrecio();
            dfTable.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        jlabel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("Listado de Vehiculos disponibles en la sucursal");

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculos);

        jlabel2.setBackground(new java.awt.Color(0, 153, 255));
        jlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar");

        javax.swing.GroupLayout jlabel2Layout = new javax.swing.GroupLayout(jlabel2);
        jlabel2.setLayout(jlabel2Layout);
        jlabel2Layout.setHorizontalGroup(
            jlabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlabel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jlabel2Layout.setVerticalGroup(
            jlabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlabel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel2MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) this.tablaVehiculos.getModel();
        //Rescatamos el indice de la fila seleccionada
        int fila = this.tablaVehiculos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un vehiculo");
        } else {
            //Rescatamos los datos de la fila seleccionada (marca, modelo, pantent,...)
            String marca = String.valueOf(this.tablaVehiculos.getValueAt(fila, 0));
            String modelo = String.valueOf(this.tablaVehiculos.getValueAt(fila, 1));
            String patente = String.valueOf(this.tablaVehiculos.getValueAt(fila, 2));
            String color = String.valueOf(this.tablaVehiculos.getValueAt(fila, 3));
            String anio = String.valueOf(this.tablaVehiculos.getValueAt(fila, 4));
            int kilometraje = Integer.parseInt(String.valueOf(this.tablaVehiculos.getValueAt(fila, 5)));
            int precio = Integer.parseInt(String.valueOf(this.tablaVehiculos.getValueAt(fila, 6)));
            //Creamos un nuevo objetivo vehiculo con los datos que rescatamos
            Vehiculo vc = new Vehiculo(marca,modelo,patente,color,anio,kilometraje,precio);
            //Llamamos al metodo modificar del menu principal y le pasamos por parametro el objeto vehiculo creado
            mp.modificarVehiculo(vc);
            JOptionPane.showMessageDialog(null, "Registro modificado!");
        }
        
    }//GEN-LAST:event_jlabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jlabel2;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
