
package ventanas;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import modelo.Vehiculo;

/**
 *
 * @author Jorge Fuentes
 * @author Fernanda Jara
 * @author Javier Torres
 * @author Miriam Zambrano
 * 
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //Listado de vehiculos disponibles en sucursal
    private ArrayList<Vehiculo> vehiculos;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setSize(950,570);
        setLocationRelativeTo(this);
        setResizable(false);
        
        vehiculos = new ArrayList();
        Vehiculo v1 = new Vehiculo("TOYOTA","Yaris","YXCE98","Blanco","2019",105670,11500000);
        Vehiculo v2 = new Vehiculo("TOYOTA","Yaris","MNET03","Rojo","2021",5600,12500000);
        Vehiculo v3 = new Vehiculo("TOYOTA","Corolla","JCFM94","Gris","2020",35570,11950000);
        Vehiculo v4 = new Vehiculo("TOYOTA","Yaris Sport","PCTD04","Gris","2020",20170,12950000);
        Vehiculo v5 = new Vehiculo("TOYOTA","Hilux","HLUX35","Gris","2021",570,19290000);
        Vehiculo v6 = new Vehiculo("NISSAN","Versa","VRSA21","Rojo","2021",1070,10870000);
        Vehiculo v7 = new Vehiculo("NISSAN","Xtrail","XTRL22","Blanco","2021",870,16150000);
        Vehiculo v8 = new Vehiculo("KIA","Seltos","SLTO12","Naranjo","2020",19500,15950000);
        Vehiculo v9 = new Vehiculo("KIA","Morning","MRNH59","Rojo","2021",0,8390000);
        Vehiculo v10 = new Vehiculo("KIA","Rio 5","KROC05","Azul","2021",0,12490000);
        Vehiculo v11 = new Vehiculo("KIA","Sportage","KASP31","Gris","2021",0,19450000);
        vehiculos.add(v1);
        vehiculos.add(v2);
        vehiculos.add(v3);
        vehiculos.add(v4);
        vehiculos.add(v5);
        vehiculos.add(v6);
        vehiculos.add(v7);
        vehiculos.add(v8);
        vehiculos.add(v9);
        vehiculos.add(v10);
        vehiculos.add(v11);
        
        InicioListado panelInicio = new InicioListado(this);
        ShowPanel(panelInicio);
    }
    
    //Metodo encargado de mostrar y ocultar los paneles del ventana principal
    private void ShowPanel(JPanel p){
        p.setSize(740,570);
        p.setLocation(0,0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    public void modificarVehiculo(Vehiculo vc){
        int pos = 0;
        //Buscamos la posición (pos) del vehiculo editado dentro del arrayList
        for(int i=0; i<vehiculos.size(); i++){
            if(vehiculos.get(i).getPatente() == vc.getPatente()){
                pos = i;
            }
        }
        //Cuando ya tenemos la posicion, la reemplazaremos por el objeto editado (vc)
        vehiculos.set(pos, vc);
    }
    
    //Metodo que devuelve el arrayList de vehiculos
    public ArrayList<Vehiculo> getArrayList(){
        return vehiculos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuBtnInicioListado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuBtnAgregar = new javax.swing.JPanel();
        jLabelAgregar = new javax.swing.JLabel();
        menuBtnBorrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuBtnCalcularCredito = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuBtnCerrarSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(13, 53, 98));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Concesionaria");

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        menuBtnInicioListado.setBackground(new java.awt.Color(24, 67, 117));
        menuBtnInicioListado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtnInicioListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnInicioListadoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");

        javax.swing.GroupLayout menuBtnInicioListadoLayout = new javax.swing.GroupLayout(menuBtnInicioListado);
        menuBtnInicioListado.setLayout(menuBtnInicioListadoLayout);
        menuBtnInicioListadoLayout.setHorizontalGroup(
            menuBtnInicioListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnInicioListadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnInicioListadoLayout.setVerticalGroup(
            menuBtnInicioListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnInicioListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuBtnAgregar.setBackground(new java.awt.Color(24, 67, 117));
        menuBtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnAgregarMouseClicked(evt);
            }
        });

        jLabelAgregar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregar.setText("Agregar vehiculo");

        javax.swing.GroupLayout menuBtnAgregarLayout = new javax.swing.GroupLayout(menuBtnAgregar);
        menuBtnAgregar.setLayout(menuBtnAgregarLayout);
        menuBtnAgregarLayout.setHorizontalGroup(
            menuBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnAgregarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnAgregarLayout.setVerticalGroup(
            menuBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBtnBorrar.setBackground(new java.awt.Color(24, 67, 117));
        menuBtnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnBorrarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Borrar vehiculo");

        javax.swing.GroupLayout menuBtnBorrarLayout = new javax.swing.GroupLayout(menuBtnBorrar);
        menuBtnBorrar.setLayout(menuBtnBorrarLayout);
        menuBtnBorrarLayout.setHorizontalGroup(
            menuBtnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnBorrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnBorrarLayout.setVerticalGroup(
            menuBtnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBtnBorrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        menuBtnCalcularCredito.setBackground(new java.awt.Color(24, 67, 117));
        menuBtnCalcularCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtnCalcularCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnCalcularCreditoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Calcular Crédito");

        javax.swing.GroupLayout menuBtnCalcularCreditoLayout = new javax.swing.GroupLayout(menuBtnCalcularCredito);
        menuBtnCalcularCredito.setLayout(menuBtnCalcularCreditoLayout);
        menuBtnCalcularCreditoLayout.setHorizontalGroup(
            menuBtnCalcularCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnCalcularCreditoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnCalcularCreditoLayout.setVerticalGroup(
            menuBtnCalcularCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnCalcularCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuBtnCerrarSesion.setBackground(new java.awt.Color(24, 67, 117));
        menuBtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnCerrarSesionMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cerrar Sesión");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout menuBtnCerrarSesionLayout = new javax.swing.GroupLayout(menuBtnCerrarSesion);
        menuBtnCerrarSesion.setLayout(menuBtnCerrarSesionLayout);
        menuBtnCerrarSesionLayout.setHorizontalGroup(
            menuBtnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnCerrarSesionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnCerrarSesionLayout.setVerticalGroup(
            menuBtnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBtnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtnInicioListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(menuBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtnCalcularCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(menuBtnInicioListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtnCalcularCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 570));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 740, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnAgregarMouseClicked
        AgregarVehiculo panelAgregar = new AgregarVehiculo(this);
        ShowPanel(panelAgregar);
    }//GEN-LAST:event_menuBtnAgregarMouseClicked

    private void menuBtnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnBorrarMouseClicked
        BorrarVehiculo panelBorrar = new BorrarVehiculo(this);
        ShowPanel(panelBorrar);
    }//GEN-LAST:event_menuBtnBorrarMouseClicked

    private void menuBtnCalcularCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnCalcularCreditoMouseClicked
        CalcularCredito panelCredito = new CalcularCredito();
        ShowPanel(panelCredito);
    }//GEN-LAST:event_menuBtnCalcularCreditoMouseClicked

    private void menuBtnInicioListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnInicioListadoMouseClicked
        InicioListado panelInicio = new InicioListado(this);
        ShowPanel(panelInicio);
    }//GEN-LAST:event_menuBtnInicioListadoMouseClicked

    private void menuBtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnCerrarSesionMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuBtnCerrarSesionMouseClicked
    
                                                 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuBtnAgregar;
    private javax.swing.JPanel menuBtnBorrar;
    private javax.swing.JPanel menuBtnCalcularCredito;
    private javax.swing.JPanel menuBtnCerrarSesion;
    private javax.swing.JPanel menuBtnInicioListado;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
